// flow-typed signature: 7a70d5a18ee6779d5ee42daa435c567f
// flow-typed version: <<STUB>>/@fortawesome/pro-duotone-svg-icons_v5.11.2/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/pro-duotone-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/pro-duotone-svg-icons' {
  declare module.exports: any;
}
