comment:
  behavior: default
  layout: "diff, flags, files"
  require_changes: false
github_checks:
  annotations: false
ignore:
  - "**/*.md"
  - "build/.*"
  - "config/.*"
  - "flow-typed/.*"
  - "node_modules/.*"
parsers:
  javascript:
    enable_partials: yes
