// flow-typed signature: a35b1666d1f44821e45c1c0c6113b45d
// flow-typed version: <<STUB>>/file-saver_v2.0.2/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-saver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-saver' {
  declare module.exports: any;
}
