// flow-typed signature: edda612aeebe1bd2fea1f40dfaf6c6fe
// flow-typed version: <<STUB>>/libphonenumber-js_v1.7.55/flow_v0.120.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libphonenumber-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libphonenumber-js' {
  declare module.exports: any;
}
