// flow-typed signature: ce4d42d96a6c3ec5fadfa188fbfd58e0
// flow-typed version: <<STUB>>/papaparse_v5.1.1/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'papaparse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'papaparse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'papaparse/Gruntfile' {
  declare module.exports: any;
}

declare module 'papaparse/papaparse' {
  declare module.exports: any;
}

declare module 'papaparse/papaparse.min' {
  declare module.exports: any;
}

declare module 'papaparse/player/player' {
  declare module.exports: any;
}

declare module 'papaparse/tests/node-tests' {
  declare module.exports: any;
}

declare module 'papaparse/tests/test-cases' {
  declare module.exports: any;
}

declare module 'papaparse/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'papaparse/Gruntfile.js' {
  declare module.exports: $Exports<'papaparse/Gruntfile'>;
}
declare module 'papaparse/papaparse.js' {
  declare module.exports: $Exports<'papaparse/papaparse'>;
}
declare module 'papaparse/papaparse.min.js' {
  declare module.exports: $Exports<'papaparse/papaparse.min'>;
}
declare module 'papaparse/player/player.js' {
  declare module.exports: $Exports<'papaparse/player/player'>;
}
declare module 'papaparse/tests/node-tests.js' {
  declare module.exports: $Exports<'papaparse/tests/node-tests'>;
}
declare module 'papaparse/tests/test-cases.js' {
  declare module.exports: $Exports<'papaparse/tests/test-cases'>;
}
declare module 'papaparse/tests/test.js' {
  declare module.exports: $Exports<'papaparse/tests/test'>;
}
