// flow-typed signature: ce4d42d96a6c3ec5fadfa188fbfd58e0
// flow-typed version: <<STUB>>/papaparse_v5.1.1/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'papaparse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'papaparse' {
  declare module.exports: any;
}
