// flow-typed signature: 16d57ee1934a770454cf0b3920ff82fd
// flow-typed version: <<STUB>>/react-scrolllock_v5.0.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scrolllock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scrolllock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scrolllock/dist' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/ScrollLock' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/TouchScrollable' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/utils' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/withLockSheet' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/withTouchListeners' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scrolllock/dist/index' {
  declare module.exports: $Exports<'react-scrolllock/dist'>;
}
declare module 'react-scrolllock/dist/index.js' {
  declare module.exports: $Exports<'react-scrolllock/dist'>;
}
declare module 'react-scrolllock/dist/ScrollLock.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/ScrollLock'>;
}
declare module 'react-scrolllock/dist/TouchScrollable.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/TouchScrollable'>;
}
declare module 'react-scrolllock/dist/utils.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/utils'>;
}
declare module 'react-scrolllock/dist/withLockSheet.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/withLockSheet'>;
}
declare module 'react-scrolllock/dist/withTouchListeners.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/withTouchListeners'>;
}
