/*
 * @flow
 */

import { Constants, Models } from 'lattice';

const { FQN } = Models;
const { OPENLATTICE_ID_FQN } = Constants;

const APP_TYPE_FQNS :Object = {
  ADDRESSES: FQN.of('app.addresses'),
  APPEARS_IN: FQN.of('app.appearsin_new'),
  ASSIGNED_TO: FQN.of('app.assignedto'),
  ATTORNEYS: FQN.of('app.attorneys'), // general.person
  ATTORNEY_CONTACT_INFO: FQN.of('app.attorneycontactinformation'),
  CONTACTED_VIA: FQN.of('app.contactedvia'),
  CONTACT_INFO: FQN.of('app.contactinformation'),
  COUNTY_ID: FQN.of('app.countyids'),
  COURT_CASES: FQN.of('app.courtcases'),
  EDUCATION: FQN.of('app.education'),
  EMERGENCY_CONTACT: FQN.of('app.emergencycontact'), // general.person
  EMERGENCY_CONTACT_INFO: FQN.of('app.emergencycontactinformation'),
  EMPLOYED_BY: FQN.of('app.employedby'),
  EMPLOYEE: FQN.of('app.employee'),
  EMPLOYMENT: FQN.of('app.employment'),
  ENROLLMENT_STATUS: FQN.of('app.enrollmentstatus'),
  FOLLOW_UPS: FQN.of('app.issue'),
  FULFILLS: FQN.of('app.fulfills'),
  HAS: FQN.of('app.has'),
  HEARINGS: FQN.of('app.hearings'),
  INMATES: FQN.of('app.inmate'),
  IS: FQN.of('app.is_new'),
  IS_EMERGENCY_CONTACT_FOR: FQN.of('app.isemergencycontactfor'),
  IS_REGISTERED_SEX_OFFENDER_IN: FQN.of('app.isregisteredsexoffenderin'),
  JAILS_PRISONS: FQN.of('app.jailsorprisons'),
  JAIL_STAYS: FQN.of('app.jailstays'),
  JAIL_STAY_LENGTH: FQN.of('app.jailstaylength'),
  LOCATED_AT: FQN.of('app.locatedat'),
  LOCATION: FQN.of('app.location'),
  MANUAL_ASSIGNED_TO: FQN.of('app.manualassignedto'),
  MANUAL_JAILS_PRISONS: FQN.of('app.manualjailsprisons'),
  MANUAL_JAIL_STAYS: FQN.of('app.manualjailstays'),
  MANUAL_JAIL_STAYS_LENGTH: FQN.of('app.manualjailstaylength'),
  MANUAL_LOCATED_AT: FQN.of('app.manuallocatedat'),
  MANUAL_OF_LENGTH: FQN.of('app.manualoflength'),
  MANUAL_SUBJECT_OF: FQN.of('app.manualsubjectof'),
  MEETINGS: FQN.of('app.meetings'),
  NEEDS_ASSESSMENT: FQN.of('app.needsassessment'), // ol.referralrequest
  OFFICERS: FQN.of('app.officer'), // general.person
  OFFICER_CONTACT_INFO: FQN.of('app.officercontactinformation'),
  OF_LENGTH: FQN.of('app.oflength'),
  ORGANIZATION: FQN.of('app.organization'),
  PART_OF: FQN.of('app.partof'),
  PEOPLE: FQN.of('app.people'),
  PERSON_DETAILS: FQN.of('app.persondetails'),
  PERSON_DETAILS_CRIMINAL_JUSTICE: FQN.of('app.person_details_criminal_justice'),
  PROBATION_PAROLE: FQN.of('app.probationorparole'),
  PROBATION_PAROLE_OFFICER: FQN.of('app.probation_or_parole_officer'),
  PROVIDED: FQN.of('app.provided'),
  PROVIDED_TO: FQN.of('app.providedto'),
  PROVIDER: FQN.of('app.organization'),
  PROVIDER_ADDRESS: FQN.of('app.provideraddress'),
  PROVIDER_CONTACT_INFO: FQN.of('app.providercontactinformation'),
  PROVIDER_EMPLOYEES: FQN.of('app.serviceprovideremployees'), // ol.employee
  PROVIDER_STAFF: FQN.of('app.serviceproviderstaff'), // general.person
  RECORDED_BY: FQN.of('app.recordedby'),
  REENTRY_EMPLOYEES: FQN.of('app.staff_employee'), // ol.employee
  REENTRY_STAFF: FQN.of('app.staff'), // general.person
  REFERRAL_REQUEST: FQN.of('app.referralrequest'),
  REGISTERED_FOR: FQN.of('app.registeredfor'),
  REPORTED: FQN.of('app.reported'),
  REPRESENTED_BY: FQN.of('app.representedby'),
  SEX_OFFENDER: FQN.of('app.sexoffender'),
  SEX_OFFENDER_REGISTRATION_LOCATION: FQN.of('app.sexoffenderregistrationlocation'), // ol.location
  STATE_ID: FQN.of('app.identification'),
  SUBJECT_OF: FQN.of('app.subjectof'),
};

const PROPERTY_TYPE_FQNS = {
  ASSIGNEE_ID: FQN.of('ol.assigneeid'),
  CATEGORY: FQN.of('ol.category'),
  CITY: FQN.of('location.city'),
  COUNTRY: FQN.of('ol.country'),
  COUNTY: FQN.of('ol.county'),
  COUNTY_ID: FQN.of('nc.SubjectIdentification'),
  DATA_SOURCE: FQN.of('ol.datasource'),
  DATE: FQN.of('general.date'),
  DATETIME_COMPLETED: FQN.of('date.completeddatetime'),
  DATETIME_END: FQN.of('ol.datetimeend'),
  DESCRIPTION: FQN.of('ol.description'),
  DOB: FQN.of('nc.PersonBirthDate'),
  EFFECTIVE_DATE: FQN.of('ol.effectivedate'),
  EMAIL: FQN.of('staff.email'),
  ENTITY_KEY_ID: OPENLATTICE_ID_FQN,
  ETHNICITY: FQN.of('nc.PersonEthnicity'),
  FIRST_NAME: FQN.of('nc.PersonGivenName'),
  FUTURE_PLANS: FQN.of('ol.futureplans'),
  GENDER: FQN.of('person.gender'),
  GENERAL_DATETIME: FQN.of('general.datetime'),
  GENERAL_NOTES: FQN.of('general.notes'),
  GENERAL_STATUS: FQN.of('general.status'),
  HIGHEST_EDUCATION_LEVEL: FQN.of('person.highesteducation'),
  IS_CELL_PHONE: FQN.of('contact.cellphone'),
  LAST_NAME: FQN.of('nc.PersonSurName'),
  LEVEL: FQN.of('ol.level'),
  MARITAL_STATUS: FQN.of('person.maritalstatus'),
  MIDDLE_NAME: FQN.of('nc.PersonMiddleName'),
  NAME: FQN.of('ol.name'),
  NOTES: FQN.of('ol.notes'),
  OL_DATETIME: FQN.of('ol.datetime'),
  OL_ID_FQN: FQN.of('ol.id'),
  OL_TITLE: FQN.of('ol.title'),
  PERSON_SEX: FQN.of('nc.PersonSex'),
  PERSON_SUFFIX: FQN.of('nc.PersonSuffix'),
  PHONE_NUMBER: FQN.of('contact.phonenumber'),
  PREFERRED: FQN.of('ol.preferred'),
  PREFERRED_METHOD_OF_CONTACT: FQN.of('ol.preferredmethod'),
  PROJECTED_RELEASE_DATETIME: FQN.of('ol.projectedreleasedatetime'),
  RACE: FQN.of('nc.PersonRace'),
  REASON: FQN.of('ol.reason'),
  RECOGNIZED_END_DATETIME: FQN.of('ol.recognizedenddate'),
  REGISTERED_FLAG: FQN.of('ol.registeredflag'),
  RELATIONSHIP: FQN.of('ol.relationship'),
  RELEASE_DATETIME: FQN.of('ol.releasedatetime'),
  SEX_OFFENDER: FQN.of('ol.sexoffender'),
  SOURCE: FQN.of('ol.source'),
  SSN: FQN.of('nc.SSN'),
  STATUS: FQN.of('ol.status'),
  STREET: FQN.of('location.street'),
  STRING_NUMBER: FQN.of('ol.stringnumber'),
  TITLE: FQN.of('person.title'),
  TYPE: FQN.of('ol.type'),
  US_STATE: FQN.of('location.state'),
  VISIT_REASON: FQN.of('visit.reason'),
  ZIP: FQN.of('location.zip'),
};

export {
  APP_TYPE_FQNS,
  PROPERTY_TYPE_FQNS,
};
